<<<<<<< HEAD
import Header from '../components/Header';
import Hero from '../components/Hero';
=======
import Head from 'next/head';

import bonequinhoComBolsas from '../assets/cliente_w.png';
import Logo from '../assets/logo.svg';
>>>>>>> main

export default function Home() {
  return (
    <div>
<<<<<<< HEAD
      <Header />
      <Hero />
=======
      <Head>
        <title>Conecta Logística | Logística Inteligente!</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>Olá mundo</h1>
        <img src={bonequinhoComBolsas} alt="Boneco" />
        <Logo />
      </main>
>>>>>>> main
    </div>
  );
}
